### ISSUE TITLE
how to stop autoupdate for totalcms

### ISSUE THREAD

**Issue by avping** [totaljs/superadmin#47]
hi, your open source stacks are great, every product of it! Im currently in love with superadmin and I have installed totaljs cms over it. 

my question is: how to stop superadmin to update totalcms after restart?

for example: plugins/pages/schemas/templates.js if I remove the spa18.css from the source to add tailwindcss and bundle it, it overwrites/update the .src by superadmin after app restarts.

**Comment by petersirka** [comment]
Hi @avping.
Thank you. Please check the structure of your CMS, here is my:

![image](https://user-images.githubusercontent.com/2414252/128751141-a8b6de9f-6bf8-4fe7-9ba8-84721b5a9143.png)

- if you restarted the app, then the framework will extract all files from the bundle so that the framework will replace your modification too
- you need to copy the file `plugins/pages/schemas/templates.js` into the root of the app like this:

```text
/bundles/cms.bundle
/plugins/pages/schemas/templates.js
/config
/index.js
```

Then the framework will extract all files from the `cms.bundle,` and it will replace the `plugins/pages/schemas/templates.js` file with your file.

Or better solution in your case:

- stop the app
- copy all files from the `.src` directory of your CMS to another folder
- remove all files from your CMS app folder
- copy back only the content from the `.src` directory
- restart the app, and you can perform all that you will need

**Comment by avping** [comment]
thank you for your suggested solution.
