### ISSUE TITLE
What ports?

### ISSUE THREAD

**Issue by FKasa** [totaljs/superadmin#9]
Readme says:

> IMPORTANT: All ports from 8000 must be free for SuperAdmin applications because SuperAdmin uses auto-generating port numbers for new applications.

Is that **ALL ports** 8000+? With or without 8000?
So: 8000, 8001, ... ,49150 ,49151?

Or I think you mean 8***, so 8000-8999.

**Comment by molda** [comment]
Hi @FKasa you're right. First app started by superadmin will have port number 8000. For 100 apps you need to make sure ports 8000-8099 are not used by any application. If you manage to install 2000 applications you are likely to run into an error since port 9999 is used by SuperAdmin. So stay below 2000 :)

**Comment by FKasa** [comment]
Superadmin-> 8000
App1    -> 8001
App2    -> 8002
App3    -> 8003
Is this correct?

If you it should be clarified in Readme.md, something along the lines of:

> IMPORTANT! Superadmin itself will use port 8000. Each app will increment from there (App1: 8001, App2: 8002,...) so make sure these ports are **unused**!

>

**Comment by molda** [comment]
No, as I said SuperAdmin is running on port 9999  so App1 -> 8000
I'll update readme to clarify it :+1:
Thanks
